// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(WebApiContext))]
    partial class WebApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.Charla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Eliminado");

                    b.Property<DateTime>("Fecha");

                    b.Property<TimeSpan>("HoraFin");

                    b.Property<TimeSpan>("HoraInicio");

                    b.Property<string>("Nombre");

                    b.Property<int>("idSala");

                    b.Property<int>("idSpeaker");

                    b.HasKey("Id");

                    b.HasIndex("idSala");

                    b.HasIndex("idSpeaker");

                    b.ToTable("Charlas");
                });

            modelBuilder.Entity("WebApi.Models.CharlaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Eliminado");

                    b.Property<int>("idAsistente");

                    b.Property<int>("idCharla");

                    b.HasKey("Id");

                    b.HasIndex("idAsistente");

                    b.HasIndex("idCharla");

                    b.ToTable("CharlaDetalles");
                });

            modelBuilder.Entity("WebApi.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacidad");

                    b.Property<bool>("Eliminado");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("WebApi.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<int>("cantidadMaximaCharlas");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("WebApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos");

                    b.Property<string>("Correo");

                    b.Property<bool>("Eliminado");

                    b.Property<string>("Nombres");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("idTipoUsuario");

                    b.HasKey("Id");

                    b.HasIndex("idTipoUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApi.Models.Charla", b =>
                {
                    b.HasOne("WebApi.Models.Sala", "Sala")
                        .WithMany("Charlas")
                        .HasForeignKey("idSala")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.Usuario", "Speaker")
                        .WithMany("charlasSpeaker")
                        .HasForeignKey("idSpeaker")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.CharlaDetalle", b =>
                {
                    b.HasOne("WebApi.Models.Usuario", "Asistente")
                        .WithMany("charlasAsistidas")
                        .HasForeignKey("idAsistente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.Charla", "Charla")
                        .WithMany("AsistentesCharla")
                        .HasForeignKey("idCharla")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.Usuario", b =>
                {
                    b.HasOne("WebApi.Models.TipoUsuario", "tipoUsuario")
                        .WithMany()
                        .HasForeignKey("idTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
